---
title: "BB512/BB612 - Special Topics in Biostatistics and Bioinformatics - Spring 2022"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r schedule, echo=FALSE}
suppressMessages(sched_df <- readxl::read_excel("misc/lectures.xlsx"))

sched_df$Slides <- sched_df$`R script` <- NULL
colnames(sched_df)[4] <- "HW"
sched_df$HW[is.na(sched_df$HW)] <- ""

# function for creating link
link_to_file <- function(text, rel_path) {
    URL <- paste0("https://github.com/egeulgen/BB512_BB612_21_22/blob/main/", rel_path)
    new_text <- kableExtra::cell_spec(text, "html", link = URL)
    return(new_text)
}

# links to HWs
sched_df$HW[3] <- link_to_file(sched_df$HW[3], "Homeworks/HW1.pdf")
sched_df$HW[6] <- link_to_file(sched_df$HW[6], "Homeworks/HW2.pdf")

# links to lectures
# links to lectures
sched_df$Subject[1] <- link_to_file(sched_df$Subject[1], "lectures/1.intro.pdf")
sched_df$Subject[2] <- link_to_file(sched_df$Subject[2], "lectures/2.EDA.pdf")
sched_df$Subject[3] <- link_to_file(sched_df$Subject[3], "lectures/3.dim_reduction.pdf")
sched_df$Subject[4] <- link_to_file(sched_df$Subject[4], "Homeworks/HW1_KEY.pdf")
sched_df$Subject[5] <- link_to_file(sched_df$Subject[5], "lectures/5.batch.pdf")
sched_df$Subject[6] <- link_to_file(sched_df$Subject[6], "lectures/6.inference.pdf")
sched_df$Subject[7] <- link_to_file(sched_df$Subject[7], "Homeworks/HW2_KEY.pdf")

# links to R exercises
sched_df$R <- ""
sched_df$R[2] <- link_to_file("EDA", "scripts/2.EDA.pdf")
sched_df$R[3] <- link_to_file("Clustering", "scripts/3.Clustering_PCA.pdf")
sched_df$R[5] <- link_to_file("Batch", "scripts/5.BatchEffects.pdf")
sched_df$R[6] <- link_to_file("Inference", "scripts/6.Inference.pdf")

kableExtra::row_spec(kableExtra::row_spec(knitr::kable(sched_df, format = "html", escape = FALSE), which(grepl("Midterm", sched_df$Subject)), bold = TRUE, background = "#F4B41A"), nrow(sched_df), bold = TRUE, background = "#E2725A")

```